NAME = push_swap.a

LIBFT = ???/ or just ft_printf?

SRCS =	main.c stacks.c error.c digits.c


OBJ = ${SRCS:.c=.o}

CC = gcc

CFLAGS = -Wall -Werror -Wextra


all: ${NAME}

clean:
		${RM} ${OBJ}

fclean: clean
		${RM} ${NAME}

re:		fclean ${NAME}

.PHONY: all clean fclean re